# Generated by Django 3.0.4 on 2021-04-20 07:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('case_id_new', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('input_text', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=256)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Success'), (3, 'No Recommendation Found')], default=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('order', models.FloatField()),
                ('category', models.IntegerField(blank=True, choices=[(1, 'Action'), (2, 'Information Request'), (3, 'Log Request')], null=True)),
                ('suggestions', models.CharField(blank=True, max_length=512, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Case')),
            ],
        ),
    ]
