# Generated by Django 3.0.4 on 2020-11-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetail',
            name='suggestions',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
